# Generated by Django 5.1.6 on 2025-02-26 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('forward', 'Forward'), ('reverse', 'Reverse')], max_length=10)),
                ('ttl', models.IntegerField(default=3600)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('CNAME', 'CNAME'), ('MX', 'MX'), ('TXT', 'TXT'), ('NS', 'NS'), ('PTR', 'PTR'), ('SRV', 'SRV'), ('CAA', 'CAA'), ('SOA', 'SOA')], max_length=10)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(max_length=255)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('ttl', models.IntegerField(default=3600)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='zones.zone')),
            ],
        ),
    ]
