# Generated by Django 5.1.6 on 2025-02-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='ns1',
            field=models.CharField(default='ns1.example.com', max_length=255),
        ),
        migrations.AddField(
            model_name='zone',
            name='ns2',
            field=models.CharField(default='ns2.example.com', max_length=255),
        ),
        migrations.AddField(
            model_name='zone',
            name='reverse_zone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zone',
            name='serial',
            field=models.BigIntegerField(default=2025010101),
        ),
        migrations.AddField(
            model_name='zone',
            name='soa',
            field=models.CharField(default='admin.example.com.', max_length=255),
        ),
        migrations.AlterField(
            model_name='zone',
            name='ttl',
            field=models.IntegerField(default=86400),
        ),
        migrations.AlterField(
            model_name='zone',
            name='type',
            field=models.CharField(choices=[('forward', 'Forward Zone'), ('reverse', 'Reverse Zone')], max_length=10),
        ),
    ]
