# Generated by Django 5.1.6 on 2025-02-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0002_zone_description_zone_ns1_zone_ns2_zone_reverse_zone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='reverse_zone',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='serial',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='type',
        ),
        migrations.AddField(
            model_name='zone',
            name='forwarders',
            field=models.CharField(blank=True, help_text='Для Forward и Redirect', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='master_ip',
            field=models.CharField(blank=True, help_text='Только для Slave-зоны', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='zone_type',
            field=models.CharField(choices=[('master', 'Master (Обслуживается локально)'), ('slave', 'Slave (Копируется с внешнего)'), ('forward', 'Forward (Пересылка на внешний)'), ('redirect', 'Redirect (Перенаправление)')], default='master', max_length=10),
        ),
    ]
