# Generated by Django 5.1.6 on 2025-02-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0003_remove_zone_reverse_zone_remove_zone_serial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='master_ip',
        ),
        migrations.AddField(
            model_name='zone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
