# Generated by Django 5.1.6 on 2025-02-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0005_alter_zone_zone_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='serial',
            field=models.IntegerField(default=20250123),
        ),
    ]
