# Generated by Django 5.1.6 on 2025-02-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0006_zone_serial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='type',
            new_name='record_type',
        ),
        migrations.AddField(
            model_name='zone',
            name='master_ip',
            field=models.CharField(blank=True, help_text='IP адрес мастера для Slave зоны', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='priority',
            field=models.IntegerField(blank=True, help_text='Для MX и SRV записей', null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='value',
            field=models.CharField(help_text='Значение записи (IP, домен, текст и т.д.)', max_length=255),
        ),
        migrations.AlterField(
            model_name='zone',
            name='zone_type',
            field=models.CharField(choices=[('master', 'Master'), ('slave', 'Slave'), ('forward', 'Forward (Cache)'), ('redirect', 'Redirect (NoCache)')], default='master', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together={('zone', 'name', 'record_type', 'value')},
        ),
    ]
