# Generated by Django 5.1.6 on 2025-02-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0007_rename_type_record_record_type_zone_master_ip_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'verbose_name': 'Зона', 'verbose_name_plural': 'Зоны'},
        ),
        migrations.AlterField(
            model_name='zone',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Имя зоны'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='ns1',
            field=models.CharField(blank=True, default='ns1.example.com', max_length=255, null=True, verbose_name='NS1'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='ns2',
            field=models.CharField(blank=True, default='ns2.example.com', max_length=255, null=True, verbose_name='NS2'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='serial',
            field=models.IntegerField(default=20250123, verbose_name='Serial'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='soa',
            field=models.CharField(blank=True, default='admin.example.com.', max_length=255, null=True, verbose_name='SOA'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='ttl',
            field=models.IntegerField(blank=True, default=86400, null=True, verbose_name='TTL'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='zone_type',
            field=models.CharField(choices=[('master', 'Master'), ('slave', 'Slave'), ('forward', 'Forward (Cache)'), ('redirect', 'Redirect (NoCache)')], default='master', max_length=10, verbose_name='Тип зоны'),
        ),
    ]
